RUN apt-get update \
 && apt-get install --no-install-recommends -y file \
 && apt clean \
 && wget -q http://snapshots.linaro.org/openembedded/lkft/sdk/sumo/intel-corei7-64/latest/lkft-x86_64-corei7-64-toolchain-2.5+linaro.sh \
 && chmod +x lkft-x86_64-corei7-64-toolchain-2.5+linaro.sh \
 && ./lkft-x86_64-corei7-64-toolchain-2.5+linaro.sh -y \
 && rm -v lkft-x86_64-corei7-64-toolchain-2.5+linaro.sh
